In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("/Users/syedalihussain/Documents/customer_churn/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")

print("Shape:", df.shape)
df.head()

Shape: (7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
# df = df.drop(columns=['customerID'])
# TotalCharges is stored as text, convert it to number
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
median_val = df['TotalCharges'].median()
df['TotalCharges'] = df['TotalCharges'].fillna(median_val)

In [7]:
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
print(df['Churn'].value_counts())

Churn
0    5174
1    1869
Name: count, dtype: int64

In [8]:
text_cols = df.select_dtypes(include='str').columns.tolist()
print("Text columns remaining:", text_cols)

Text columns remaining: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   str
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   str
 3   Dependents        7043 non-null   str
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  Contract          7043 non-null   str
 15  PaperlessBilling  7043 non-null   str
 16  PaymentMethod     7043 non-null   str
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   float64
 19  Churn             7043 non-null   int64
dtypes: float64(2), int64(3), str(15)
memory usage: 1.1 MB

In [10]:
le = LabelEncoder()
for col in text_cols:
    df[col] = le.fit_transform(df[col])
    print(f'{col} encoded')

print(df.dtypes)

gender encoded
Partner encoded
Dependents encoded
PhoneService encoded
MultipleLines encoded
InternetService encoded
OnlineSecurity encoded
OnlineBackup encoded
DeviceProtection encoded
TechSupport encoded
StreamingTV encoded
StreamingMovies encoded
Contract encoded
PaperlessBilling encoded
PaymentMethod encoded
gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod         int64
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

In [11]:
X = df.drop(columns=['Churn'])
y = df['Churn']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (7043, 19)
y shape: (7043,)

In [12]:
scaler = StandardScaler()
num_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
X[num_cols] = scaler.fit_transform(X[num_cols])
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,-1.277445,0,1,0,0,2,0,0,0,0,0,1,2,-1.160323,-0.994242
1,1,0,0,0,0.066327,1,0,0,2,0,2,0,0,0,1,0,3,-0.259629,-0.173244
2,1,0,0,0,-1.236724,1,0,0,2,2,0,0,0,0,0,1,3,-0.362660,-0.959674
3,1,0,0,0,0.514251,0,1,0,2,0,2,2,0,0,1,0,0,-0.746535,-0.194766
4,0,0,0,0,-1.236724,1,0,1,0,0,0,0,0,0,0,1,2,0.197365,-0.940470

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size= 0.2, stratify=y
)
print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (5634, 19)
Test size: (1409, 19)

In [15]:
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

In [16]:
train_data = X_train.copy()
train_data['Churn'] = y_train.values

test_data = y_train.copy()
test_data['Churn'] = y_test.values

train_data.to_csv("/Users/syedalihussain/Documents/customer_churn/data/processed/train.csv", index=False)
test_data.to_csv("/Users/syedalihussain/Documents/customer_churn/data/processed/test.csv", index=False)

print("Train and test data saved to data/processed/!")

Train and test data saved to data/processed/!

In [17]:
import os

path = "/Users/syedalihussain/Documents/customer_churn/data/processed/"

print("Files in processed folder:")
print(os.listdir(path))

Files in processed folder:
['test.csv', 'cleaned_churn.csv', 'train.csv']

In [18]:
train_check = pd.read_csv("/Users/syedalihussain/Documents/customer_churn/data/processed/train.csv")
test_check = pd.read_csv("/Users/syedalihussain/Documents/customer_churn/data/processed/test.csv")

print("Train shape:", train_check.shape)
print("Test shape:", test_check.shape)

print("\nTrain columns:", train_check.columns.tolist())
print("Test columns:", test_check.columns.tolist())

Train shape: (5634, 20)
Test shape: (5635, 1)

Train columns: ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']
Test columns: ['Churn']

In [19]:
X_train = X_train.fillna(X_train.median())
X_test = X_test.fillna(X_train.median())  # Use train median for test too

# Combine and save
train_data = X_train.copy()
train_data['Churn'] = y_train.values

test_data = X_test.copy()
test_data['Churn'] = y_test.values

# Save
train_data.to_csv("/Users/syedalihussain/Documents/customer_churn/data/processed/train.csv", index=False)
test_data.to_csv("/Users/syedalihussain/Documents/customer_churn/data/processed/test.csv", index=False)

print("Train shape:", train_data.shape)
print("Test shape:", test_data.shape)
print("\nTrain columns:", train_data.columns.tolist())

Train shape: (5634, 20)
Test shape: (1409, 20)

Train columns: ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']